management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

spring:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      printer:
        enabled: true
      file-extensions: .graphql
    http:
      path: /graphql
  web:
    error:
      include-message: never

grpc:
  server:
    port: 9090
